analyzer:
  errors:
    lines_longer_than_80_chars: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
